### ISSUE TITLE
Not working wit generic U2F fido devices

### ISSUE THREAD

**Issue by Dissimilis** [brucedog/U2F_Core#11]
bfoster.me does not work with  generic U2F device. Tried these:
https://www.ftsafe.com/products/FIDO/NFC
https://hypersecu.com/products/hyperfido

Works fine with github, google and hypersecu demo app (https://u2fdemo.hypersecu.com/signup <- has a glass mode for debugging).

Does your lib works only with Yubikey?

**Comment by Dissimilis** [comment]
Light on my keys does not start flashing. I can help debug, just say what exact info do you need.

**Comment by brucedog** [comment]
I am assuming that the failure happens at the registration. Right?  Do you get any error like unknown error try again?  Also what browser are you using?

**Comment by brucedog** [comment]
I was not able to reproduce. I order a HyperFIDO mini from Amazon and was able to register and login in with the repo source.
