### ISSUE TITLE
exception of type 'U2F.Core.Exceptions.U2fException' was thrown.

### ISSUE THREAD

**Issue by Earthweb-EWS** [brucedog/U2F_Core#14]
When register an account and pair my Solokey, the following error is shown on screen:
exception of type 'U2F.Core.Exceptions.U2fException' was thrown.

https://solokeys.com/

**Comment by brucedog** [comment]
What is the version of U2F.Core you are using and what is your OS?

**Comment by Earthweb-EWS** [comment]
Sorry i dit not mention it. It's on your demo site.

**Comment by Earthweb-EWS** [comment]
I've tried today and the problem is solved.
