### ISSUE TITLE
Remove Bouncy Castle Dependency

### ISSUE THREAD

**Issue by kspearrin** [brucedog/U2F_Core#3]
Would you be open to dumping the bouncy castle dependency in favor of standard framework crypto or are you trying to keep everything 1-1 with the java implementation? With .NET Core 2.0 we should be able to do all of the needed crypto.

**Comment by brucedog** [comment]
I didn't really choose Bouncy Castle for the 1-1 with the java library I did it because the library is pretty simple to use. I'm all for using the built in .NET Core 2.0 crypto so long that it works (I see no reason why it wouldn't).

**Comment by kspearrin** [comment]
.NET Core 2 landed today so might to start looking into this more.

**Comment by brucedog** [comment]
I plan to create a dev branch to explore the possibility of remove the bouncy castle dependency.

**Comment by brucedog** [comment]
I created the branch "PureDotNetCore" to test the possibility of removing the bouncy castle dependency. I ran to a road block as I was not able to verify the signature generated by a Yubico key. It seems that 71-73 ASN.1 signature is not compatible with .NET and I could not find a solution for converting the signature. I will keep the branch open in case I find a solution.

**Comment by TomCJones** [comment]
i tried to clone Pure branch with vs 2017 and with git desktop.
Neither finds that branch.
Do you or I need to do some magic to make it available?

**Comment by TomCJones** [comment]
not sure what happened, but a few hours later i was able to git the pure branch.  odd.

**Comment by brucedog** [comment]
Closing issue as the project now uses purely .NET core.

**Comment by kspearrin** [comment]
Great! I'll look forward to upgrading with the next release.

**Comment by brucedog** [comment]
Done. https://www.nuget.org/packages/U2F.Core/2.0.0
