### ISSUE TITLE
Firefox incompatibility 

### ISSUE THREAD

**Issue by jclawrence18** [brucedog/U2F_Core#36]
Should this work in Firefox? 

I am using U2F.Core in my own application and it works great in Chrome. I see odd behavior in Firefox. Device registration works fine, but Authenticating with the device gives an errorCode 2.

When trying to use your demo site in Firefox, it does not work for me at all (device does not enable for input). 

GitHub, Facebook, other U2F implementations work fine.

**Comment by brucedog** [comment]
Hey,

I just tried to reproduce it with Firefox and it worked for me. Maybe check that Firefox has security.webauth.u2f set to true in the about:config page. 

Thanks.
