### ISSUE TITLE
VS2017 Requirement

### ISSUE THREAD

**Issue by JeffFranczak** [brucedog/U2F_Core#7]
I am unable to open the solution source code in VS2015 because the VS2017 csproj files are not backwards compatible with VS2015.

Thinking about creating a new empty ASP.Core project in VS2015 and trying to manually copy the U2F_Core source files into the empty VS2015 project. Do you think manually porting the source to VS2015 would work? Can you offer any guidance or suggestions on reconstructing from a new project?

I realize I could get the compiled U2F_Core DLL via NuGet but I'd really like to work directly with the source to understand how it works.

The overall goal is investigate using the library with a VS2015 ASP.Core 1.1 web application (full-framework 4.5.2) with ASP.NET Core Identity.

Thanks!

**Comment by brucedog** [comment]
Hey Jeff,

You should be able to manually copy the cs files into the VS2015 project without issue. You would just need to do a copy paste then add them via add exist item. 

Just as a side note VS2017 is free so you could always try that.

Let me know if you have any other questions.

**Comment by JeffFranczak** [comment]
Hi Bryce, I was able to create a new VS2015 solution, manually create the two main projects, and then manually copy the files from your VS2017 solution into my VS2015 solution. Got everything compiled and stepped through the code up to the point of registering a new user. Ordered a couple Yubico FIDO U2F Security Keys last week to experiment with later this month. Thanks again for your efforts on this project.

**Comment by brucedog** [comment]
Hey Jeff

Glad you were able to get it working in VS2015. As a side note I noticed that my project is not as up to date as the java implementation so I will be making changes soon.
