### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by JeffFranczak** [brucedog/U2F_Core#8]
Hi Bryce,

My Yubico FIDO U2F key is working with the Yubico's test site  (https://demo.yubico.com/u2f) using both Chrome 63 and FF 57.0.2.

I also have your U2F test application working with Chrome 63. However, I've **not** been able to get it to work with FF 57.0.2.  With FF, the Finish Authentication page displays but the key never starts blinking. I also tried using the latest u2f-api (https://demo.yubico.com/js/u2f-api.js) but neither Chrome or FF works with the test app with the latest api--the key never starts blinking on the Finish Authentication page.

Maybe you've run into this sort of thing before? Thanks for any help or ideas you have.

Best,

- Jeff

**Comment by brucedog** [comment]
Hey Jeff,

I haven't done anything testing with FF. What U2F plugin are you using with FF to test? 

The latest u2f-api has breaking changes from the original api. I will update the project to match the latest api.

Thanks,
Bryce

**Comment by JeffFranczak** [comment]
Thanks Bryce, FF 57 includes U2F natively now--just need to enable it in config (no plug in required anymore). Great news, right! I suspected there might be breaking changes in the new u2f-api. Thanks for confirming that. Look forward to project update. Best, - Jeff

**Comment by brucedog** [comment]
Hey Jeff,

The project has been updated to use the latest (1.1) u2f javascript so if you go to the about:config in FireFox and change the key "security.webauth.u2f" value to true this demo will work. As a side note the project has been updated to netstandard 2.0 and the nuget packages are now signed as well.
